version: "3.7"
services:
    postgres:
        container_name: postgres_db
        image: 'postgres:13.1-alpine'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: mygameslib
    backend-spring-boot:
        image: 'docker-spring-boot-postgres:latest'
        depends_on:
            - postgres
        container_name: backend-spring-boot
        build:
            dockerfile: docker/backend/Dockerfile
            context:    ../
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/mygameslib
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=root
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update