CREATE TABLE games
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title    VARCHAR(255),
    rating   INTEGER,
    cover_url VARCHAR(255),
    platform VARCHAR(255),
    CONSTRAINT pk_games PRIMARY KEY (id)
);